name: Commit Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@v4
        if: github.event_name == 'pull_request'
        with:
          command: check
          args: --from ${{ github.event.pull_request.base.sha }}
